language: cpp
compiler: gcc
sudo: require
dist: trusty

install:
    - sudo apt-get -y install automake gcc make libx11-dev libxext-dev libxi-dev libfreetype6-dev libfontconfig1-dev zlib1g-dev libjpeg-dev libpng12-dev
    - sudo add-apt-repository -y ppa:ondrej/autotools
    - sudo apt-get -y update
    - sudo apt-get -y install automake-1.15
    
script:
  - bash ./configure --prefix=/usr
  - make -j$(nproc)
  - make install DESTDIR=$(readlink -f appdir) ; find appdir/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./AzPainter*.AppImage https://transfer.sh/AzPainter-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - ls -lh out/* # Assuming you have some files in out/ that you would like to upload
  - chmod a+x upload.sh
  - bash ./upload.sh ./AzPainter*.AppImage

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
